_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  standard__front_page:
    weight: -45
    menu_name: main
    parent: ''
    enabled: false
    expanded: false
