_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 2098cbe4-e0d3-451c-b993-74acca98165d
name: 'University Libraries'
mail: Lib-WebDev@fsu.edu
slogan: ''
page:
  403: ''
  404: /node/27
  front: /node/41
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
